#When changing auto click interval, by how much should it change
#Range: 1 ~ 9999999
ticksStep = 1
#The minimal auto click interval
#Range: 1 ~ 9999999
minTicksBetweenClicks = 1
#The maximal auto click interval possible before looping back to the minimum
#Range: 1 ~ 9999999
maxTicksBetweenClicks = 10

